language: ruby
sudo: false
cache: bundler
rvm: 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
install: bundle install
script:
    - bundle exec jekyll build  -d _site/www.openmicroscopy.org
    - bundle exec htmlproofer ./_site --only_4xx
